name: mosaic-production
channels:
  - conda-forge
dependencies:
  # Shared Python
  - python=3.11
  - pip

  # dependencies for the earthdem-mosaic package
  - click
  - pydantic-settings
  - rasterio
  - parsl
  - pytest

  # dependencies for the rema-mosaic package
  - click
  - pydantic-settings

  # create_dem_metadata.py imports
  - numpy
  - pandas
  - geopandas
  - shapely

  # proj_issame.py imports
  - gdal=3.7.2
