[project]
name = "rema_mosaic"
description = "A package for executing the processing stages for REMA mosaic development."
version = "0.1.0"
requires-python = ">= 3.11"
dependencies = [
    "click",
    "pydantic-settings",
]

[project.scripts]
rema-mosaic = "rema_mosaic.cli:cli"
